# RepoRef example config
# Put this file in ~/.repo-ref/config.yml

repos:
  - name: fastmcp
    alias: [fmcp, fastmcp]
    url: https://github.com/punkpeye/fastmcp.git
    description: "FastMCP is a TypeScript MCP framework"
    defaultPath: src
    branches:
      - name: main
        description: "Main branch"
